### ISSUE TITLE
Unable to run queries after archived with asar

### ISSUE THREAD

**Issue by Wlackson** [nuintun/node-adodb#19]
My app pulls data from an .mdb file quite fine using this plugin.
The .mdb file is located on a windows 8 x64 machine  on C:\storage folder.
After archiving my app for distribution/installation usin asar my app is no longer able to run queries. It simply fails to read the file an run any queries.
Any solution/workaround on this? please? :)

**Comment by nuintun** [comment]
Sorry, because use `JScript` and `Microsoft.Jet.OLEDB.4.0`, only support windows.

**Comment by evanxg852000** [comment]
Sorry @nuintun  this is issue related to asas package that you might need to correct in this repo. It's not because of JScript and Microsoft.Jet.OLEDB.4.0 . The the node-adodb does not work on Windows if you package with asar enabled.
It says the module is not found ... so maybe look into resolving the modules `app.asar.unpacked can do`

may track down to see if i can contribute
