### ISSUE TITLE
Spawn C:\WINDOWS\SysWOW64\cscript.exe error

### ISSUE THREAD

**Issue by sarj21** [nuintun/node-adodb#78]
So I'm working on something that requires an Access DB and it seems to work just fine in development mode. (Running on electron/vue)
Development mode seems to be run on a localhost web server where as I don't think production is. I am not quite sure how to give the tool the access it needs but I am getting:

```
Spawn C:\WINDOWS\SysWOW64\cscript.exe error
```
and
```
exitCode: 1
"Uncaught Fatal Exception"
```

in child process, so its an issue with childProcess.spawn()

I've added like everything I can think of to the PATH and that doesn't seem to do it :(

Any ideas, ways to debug this, or help would be appreciated!

**Comment by sarj21** [comment]
Oops. Looks like this is a duplicate of #75

**Comment by lega0208** [comment]
Yeah, so I had this issue a few months ago and figure out the problem. Basically [this](https://electronjs.org/docs/tutorial/application-packaging#executing-binaries-inside-asar-archive). Packaged Electron projects don't play well with child_process.spawn. And also cwd() doesn't work properly in asar files, that may have also contributed. I forget.

But the workaround is the following:
1. In your packager settings, add a glob that matches the node-adodb package to the [asar.unpack](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#asar) setting.
2. Go to [line 13 of proxy.js](https://github.com/nuintun/node-adodb/blob/master/lib/proxy.js#L13) and change it so that it matches the unpacked directory. The way I did this was I think I changed `require.resolve('./adodb')` to `require(path.resolve('./adodb').replace('app.asar', 'app.asar.unpacked'))` or something like that.

Either way I published my own npm package to make things easier for myself, you can try it out if you want, and see if it works for you. It doesn't use the latest version though so just be aware of that. Just don't forget to add the unpacked setting or it won't work.

Hope it works out for you. Cheers.

**Comment by HaveF** [comment]
Have you fix it with the reference?

**Comment by mohamadfg-dev** [comment]
use this code : 
```
    const ADODB = require('node-adodb');
    // ADODB.debug = true;
    const connection = ADODB.open('Provider=Microsoft.ACE.Oledb.12.0;Data Source=**(Your location database)**;', process.arch.includes('64'));
    
    connection.query('SELECT * FROM Table1').then(data => {
        console.log(JSON.stringify(data));
    }).catch(error => {
        console.error(JSON.stringify(error))
    });
```
